# -*- coding: utf-8 -*-
"""pull_exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GWyp8lCD_wvLHC5dYMQ_gAfEmVc2oUUp
"""

!pip install requests

import requests
import json
import time

# ===== API-Ninjas Setup =====
api_ninjas_key = 'JUQZNe1cWZOx//Za33Y4Vw==8HKjd8kaR6LwQsGW'  
headers = {'X-Api-Key': api_ninjas_key}

# ===== Initialize storage =====
strength_exercises = {}   # strength by muscle
cardio_exercises = []
flexibility_exercises = []

# Flexibility-related muscles
flexibility_muscles = ['abdominals', 'lower_back', 'neck', 'calves', 'hamstrings', 'glutes']

# Flexibility keywords
flexibility_keywords = ['stretch', 'plank']

# ===== Pull Strength Exercises =====
url_strength = 'https://api.api-ninjas.com/v1/exercises?type=strength&limit=100'
response_strength = requests.get(url_strength, headers=headers)

if response_strength.status_code == 200:
    strength_data = response_strength.json()
    for exercise in strength_data:
        name_lower = exercise['name'].lower()
        muscle = exercise['muscle'].lower()

        if muscle in flexibility_muscles and any(keyword in name_lower for keyword in flexibility_keywords):
            flexibility_exercises.append(exercise)
        else:
            if muscle not in strength_exercises:
                strength_exercises[muscle] = []
            strength_exercises[muscle].append(exercise)
else:
    print(f"Error pulling strength exercises: {response_strength.status_code}")

# ===== Pull Cardio Exercises =====
url_cardio = 'https://api.api-ninjas.com/v1/exercises?type=cardio&limit=100'
response_cardio = requests.get(url_cardio, headers=headers)

if response_cardio.status_code == 200:
    cardio_data = response_cardio.json()
    cardio_exercises.extend(cardio_data)
else:
    print(f"Error pulling cardio exercises: {response_cardio.status_code}")

# ===== Pull Additional Flexibility Exercises (by flexibility muscles) =====
for muscle in flexibility_muscles:
    url_flex = f'https://api.api-ninjas.com/v1/exercises?muscle={muscle}&limit=100'
    response_flex = requests.get(url_flex, headers=headers)
    if response_flex.status_code == 200:
        flex_data = response_flex.json()
        for exercise in flex_data:
            name_lower = exercise['name'].lower()
            muscle_name = exercise['muscle'].lower()

            if any(keyword in name_lower for keyword in flexibility_keywords):
                flexibility_exercises.append(exercise)
            else:
                if muscle_name not in strength_exercises:
                    strength_exercises[muscle_name] = []
                strength_exercises[muscle_name].append(exercise)
    else:
        print(f"Error pulling flexibility exercises for {muscle}: {response_flex.status_code}")

# ===== Deduplicate Exercises by Name so Exercises are not repeated =====
def deduplicate_by_name(exercise_list):
    seen = set()
    unique = []
    for ex in exercise_list:
        if 'name' in ex and ex['name']:
            name = ex['name'].lower().strip()
            if name not in seen:
                unique.append(ex)
                seen.add(name)
    return unique

def deduplicate_strength_dict(strength_dict):
    deduped = {}
    for muscle, exercises in strength_dict.items():
        deduped[muscle] = deduplicate_by_name(exercises)
    return deduped

# Apply deduplication
strength_exercises = deduplicate_strength_dict(strength_exercises)
cardio_exercises = deduplicate_by_name(cardio_exercises)
flexibility_exercises = deduplicate_by_name(flexibility_exercises)

# ===== Save to JSON =====
all_exercises = {
    "strength": strength_exercises,
    "cardio": cardio_exercises,
    "flexibility": flexibility_exercises
}

with open('all_exercises.json', 'w') as f:
    json.dump(all_exercises, f, indent=4)

# ===== Final Summary =====
total_strength = sum(len(exs) for exs in strength_exercises.values())
print(f"Saved {total_strength} unique strength exercises (grouped by muscle).")
print(f"Saved {len(cardio_exercises)} unique cardio exercises.")
print(f"Saved {len(flexibility_exercises)} unique flexibility exercises.")
print("All exercises saved to all_exercises.json")

